-- MySQL Script generated by MySQL Workbench
-- Sat May 24 16:06:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROLES` (
  `rol_codigo` INT NOT NULL,
  `rol_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rol_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIOS` (
  `rol_codigo` INT NOT NULL,
  `usuario_codigo` INT NOT NULL,
  `usuario_nombres` VARCHAR(100) NOT NULL,
  `usuario_apellidos` VARCHAR(100) NOT NULL,
  `usuario_identificacion` VARCHAR(20) NOT NULL,
  `usuairo_email` VARCHAR(50) NOT NULL,
  `usuario_pass` VARCHAR(200) NOT NULL,
  `usuario_estado` TINYINT NOT NULL,
  PRIMARY KEY (`usuario_codigo`),
  INDEX `fk_usuarios_roles_idx` (`rol_codigo` ASC),
  CONSTRAINT `fk_usuarios_roles`
    FOREIGN KEY (`rol_codigo`)
    REFERENCES `mydb`.`ROLES` (`rol_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
